#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Cargando ultimo tema
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Si tienes compton o picom
if [ -x "$(command -v compton)" ]; then
  compton --config $SCRIPTPATH/compton.conf &> /dev/null & 
elif [ -x "$(command -v picom)" ]; then
  picom &> /dev/null & 
fi

# Cargando theme.toml
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

# Fondo de pantalla
~/.fehbg

# Xmobar config
index=0
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read size
do 
   leftwm-state -w $index -t $SCRIPTPATH/template.liquid | xmobar -d -p "$size" $SCRIPTPATH/xmobar-config.hs &
   let index=index+1
done
